# Generated by Django 4.2.9 on 2024-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catgories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
