# Generated by Django 4.2.9 on 2024-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_product_updateat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
