# Generated by Django 4.2.9 on 2024-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_category_product_catgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catgory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('computer', 'computer')], max_length=50, null=True),
        ),
    ]
